name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      id: ok
      run: echo ::set-output name=action_fruit::strawberry
    - name: pritnt ok
      run: echo "${{ steps.ok.outputs.action_fruit }}"
